databases:
  - name: hallyza
    databaseName: hallyzaDb
    user: hallyza
    plan: free
    ipAllowList: []

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec bin/dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hallyzaDb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: FALSE
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
