meta_name: "Dra Hállyza Rodrigues"
meta_title: "Dra. Hállyza | Ginecologia"
meta_description: "Ginecologia Regenarativa e Funcional, Saúde Vaginal"
meta_image: "metapic.png" # should exist in `app/assets/images/`
# twitter_account: "@your_twitter_account"
